# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Messy Mompreneur
email: messymompreneur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Candid conversations about the messy and the beautiful.
# baseurl: "/docs" # the subpath of your site, e.g. /blog
domain: "messymompreneur.com"
url: "https://messymompreneur.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: GFM

author:
  name: Messy Mompreneur
  email: messymompreneur@gmail.com

header_pages:
  - subscribe.md
  - news.md
  # Removed guest until the podcast starts again
  # - guest.md
  - about.md

# Google Analytics
google_analytics: G-WQBJ835NQM

# Apple Podcasts RSS Info
podcast:
  owner:
    name: Alysha Sanford
    email: messymompreneur@gmail.com
  explicit: "no"
  image: /assets/img/podcast-cover.png
  category-one: "Business"
  subcategory-one: "Entrepreneurship"
  category-two: "Kids &amp; Family"
  subcategory-two: "Parenting"
  category-three: "Education"
  subcategory-three: "Self-Improvement"
  keywords-tags: "Mom,moms,mom-podcast,mompreneur,mompreneurs,messy-mompreneur,messy-mompreneur-podcast,entrepreneur,entrepreneurs,motherhood,work-life-balance,work-at-home-mom,working-mom,mompreneur-life,female-entrepreneur,parenthood,parenting,parenting-podcast,parenthood-podcast,mom-boss,mom-boss-podcast,lady-boss,lady-boss-podcast,boss-mom,boss-mom-podcast,podcast,podcasts,podcasters,podcast-show,podcast-junkie"
  description: >-
   Hello and welcome to the Messy Mompreneur podcast! I’m so happy to have you here!


   My name is Alysha Sanford and I’m your show host!


   I’m a newer, first-time, work-at-home-mama navigating the highs and lows of entrepreneurship. Running a business, working full time, or chasing career dreams in general while also raising littles and maintaining the home can be so challenging. Especially if you don’t have a strong, local support system or aren’t great about asking for help. I personally struggle with that last one.


   On this podcast, I plan to touch on all aspects of mompreneur life, including productivity, time management, tips and hacks, self-care, marketing, home-making and parenting in general.


   I want to give a voice to others who might be struggling and, as an introvert, I want to get more comfortable with my own voice. This will likely be an audio only show because I know that most of you are likely multitasking while listening. I also want to be able to accommodate any guests on the show who’d prefer to stay somewhat private.


   You’ll hear from fellow mompreneurs, other inspiring guests and eventually I hope to chat with some industry experts as well. We’ll be having conversations about the messy, the tough and the beautiful. I want you to listen, feel seen and finish each episode feeling a sense of encouragement and community.


   If you haven’t already, I’d be so grateful if you’d take a minute to subscribe to the podcast and leave a review. If you’d share this podcast with other’s that may find it helpful, that would also be incredibly appreciated. I’d really love to connect with you on social media! Shoot me a DM with any specific topics you want to hear more about or questions that you’d like me to ask fellow mompreneurs during guest interviews. You can find me on most platforms with the handle @messymompreneur. I’ll share my contact info in the show notes as well.

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/messymompreneur" }
    - { platform: instagram, user_url: "https://instagram.com/messymompreneur" }
    - { platform: pinterest, user_url: "https://www.pinterest.com/messymompreneur/" }

# Build settings
remote_theme: jekyll/minima
# remote_theme: pages-themes/slate@0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
